name: 'Gitbook CI'
on:
  push:
    branches:
      - master
    # paths:
    #   - 'gitbook_src/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    - name: Build
      run: |
        rm -rf docs
        cd gitbook_src
        gitbook build
        cd ..
        mv gitbook_src/_book docs
        echo "gitbook build"

    - name: deploy
      run: |
        echo "gitbook deploy"

