name: 'Gitbook CI'
on:
  push:
    branches:
      - master
    paths:
      - 'gitbook_src/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd {{$GITHUB_WORKSPACE/gitbook_src}}
        ls
        echo "gitbook build"

    - name: deploy
      run: |
        echo "gitbook deploy"

