name: 'Gitbook CI'
on:
  push:
    paths:
      - 'gitbook/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "gitbook build"

    - name: deploy
      run: |
        echo "gitbook deploy"

